version: '2'
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll build --watch
    tty: true
    volumes:
        - ./app:/srv/jekyll
        - ./build:/srv/build
        - ./bundle:/usr/local/bundle
  server:
    image: nginx:stable
    ports:
        - "127.0.0.1:8080:80"
    volumes:
        - ./build:/usr/share/nginx/html:ro
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
